import './globals.css'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'

const inter = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-black mx-16 text-white'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
